# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d70cf7c242481f88e23dee7ca8770c8c0e73b852a9a27f7eb0de3e30491468e13065ba10d29e5006cf6860aaeda8a26d557409f15d0f61d34ef47e3935a269f4

test:
  secret_key_base: e2435669ab9e22045d05469477998de2673ae5f159c97c8f9544635fa0f9d70b1b7ee02bc23c697e0dd008198fee60cc373724bc857ea6a8d08195ae7824acb8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
